name: Check Version and Build

on:
  schedule:
    - cron: "0 * * * *" # Check every hour
  push:
    branches:
      - main

jobs:
  check_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest release
        id: get_latest_release
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/inotia00/revanced-patches/releases/latest | jq -r .tag_name)
          echo "Latest version is $LATEST_VERSION"
          echo "::set-output name=latest::$LATEST_VERSION"

      - name: Compare versions
        id: compare_versions
        run: |
          CURRENT_VERSION=$(cat VERSION.txt) # Assuming the current version is stored in VERSION.txt
          echo "Current version is $CURRENT_VERSION"
          if [ "$CURRENT_VERSION" != "${{ steps.get_latest_release.outputs.latest }}" ]; then
            echo "New version available"
            echo "::set-output name=new_version::true"
          else
            echo "No new version"
            echo "::set-output name=new_version::false"
          fi

  build:
    runs-on: ubuntu-latest
    needs: check_version
    if: needs.check_version.outputs.new_version == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: |
          # Add your build commands here
          echo "Building the project..."
